sonar.projectKey=adsPucrs-devops-projeto
sonar.organization=welandrade
sonar.projectName=adsPucrs-devops-projeto
sonar.sources=app
sonar.exclusions=**/*_test.go
sonar.tests=app
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
